# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.8.0
_src_path: gh:algorandfoundation/algokit-python-template
author_email: matsganz@gmail.com
author_name: Rahmat Eka
contract_name: session
deployment_language: python
preset_name: starter
project_name: session1-contracts

